---
  dataSource: "issues"
  prefix: ""
  ignore-tags-with: "fuse"
  onlyMilestones: false
  groupBy: {
    "Enhancements": ["cat/enhancement", "cat/feature"],
    "Bug Fixes": ["cat/bug"]
  }
  ignore-issues-with: [
    "wontfix"
  ]
  "template": {
        "issue": "- [{{text}}]({{url}}) {{name}}"
  }
  changelogFilename: "CHANGELOG.md"
