version: 2
jobs:
  build:
    working_directory: /workspace
    docker:
    - image: openjdk:8-jdk
    environment:
      MAVEN_OPTS: -Xmx1G
      DOCKER_VERSION: 17.04.0-ce
    branches:
      ignore:
        gh-pages

    steps:
      - setup_remote_docker

      - checkout

      - restore_cache:
          key: atlasmap-m2

      - run:
          name: Maven
          command: ./mvnw --batch-mode -Pfull -Pfabric8 install

      - save_cache:
          key: atlasmap-m2
          paths:
          - ~/.m2

      - run:
          name: Collect junit reports
          command: |
            mkdir ./junit/
            find . -type f -regex ".*/target/.*-reports/.*xml" -exec cp {} ./junit/ \;

      - store_test_results:
          path: ./junit

      - store_artifacts:
          path: ./junit

      - deploy:
          command: |
            if [ "${CIRCLE_PROJECT_USERNAME}" != "atlasmap" ]; then
              exit 0
            fi

            curl -fsSL https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz | tar xz -C /usr/bin --strip-components 1

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              DOCKER_IMAGE_TAG="latest"
            elif [[ "${CIRCLE_TAG}" =~ ^v[0-9]+(\.[0-9]+){2} ]]; then
              DOCKER_IMAGE_TAG="${CIRCLE_TAG}"
            fi

            if [ -z "${DOCKER_IMAGE_TAG}" ]; then
              exit 0
            fi

            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push atlasmap/atlasmap:${DOCKER_IMAGE_TAG} | cat -

            sh atlas-docs/ci-docs.sh